### ISSUE TITLE
Promise support?

### ISSUE THREAD

**Issue by zixia** [simonepri/pidtree#1]
I'd like to add Promise support to the library because it's my favourite.

For example: 

```js
const stat = await pidtree(process.pid)
```

How do you think?

**Comment by simonepri** [comment]
Yes I would prefer that too.
But the point was to make it compatible also on old versions of node.

What we can do is to check if a callback is passed and if it's not the case then we can return a promise.

What do you think?

**Comment by soyuka** [comment]
:+1: a wrapper like this is good!

**Comment by simonepri** [comment]
@soyuka we can do the same on pidusage instead of having a separate package to promisify it.
What do you think?

**Comment by zixia** [comment]
Great, I think the following code will do it:

```js
if (!Promise) {
  const Promise = require('es6-promise-polyfill').Promise
}

function cb_n_promise(pid, cb) {
  if (cb && typeof cb === 'function') {
    // callback here...
  } else {
    // Promise here...
  }
}

**Comment by simonepri** [comment]
Is the dependency necessary?
If I pass the callback I never use the Promise part so it should be safe on old versions of node

**Comment by soyuka** [comment]
> @soyuka we can do the same on pidusage instead of having a separate package to promisify it.

On node 4 there should already be a `Promise` object (no need to polyfill). 

I'm mitigated, if the following doesn't cost too much it's good enough and allows the user to keep only 1 package:

```
function exists(path, cb) {
  return new Promise(function(resolve, reject) {
    doSomething(function(err, res) {
      if(cb) cb(err, res)
      return err ? reject(err) : resolve(res)
    })
  })
}
```

**Comment by simonepri** [comment]
We just need to do this inside the `index.js`

```
if (cb) return tree(pid, options, cb)
return pify(tree)(options)
```

**Comment by soyuka** [comment]
pify is slow (plays a lot with arguments) and gives you a new unneeded dependency ^^

**Comment by simonepri** [comment]
Actually I was not thinking to use the pify package but just something like this:
```
function pify(fn) {
  return function (options) {
    return new Promise(function (resolve, reject) {
       fn(options, function(err, data) {
         if (err) return reject(err)
         resolve(data)
       }
    })
  }
}
```

**Comment by soyuka** [comment]
:+1:
