### ISSUE TITLE
Compatibility with esbuild

### ISSUE THREAD

**Issue by ohana54** [simonepri/pidtree#16]
Hi,
We started using [esbuild](https://esbuild.github.io/), a new super fast JS compiler, and it doesn't support or intends to support dynamic requires. This means we can't use `pidtree` due to this line: https://github.com/simonepri/pidtree/blob/5ebe846a9797657ac5b77c4c312f0226c7b75ccb/lib/get.js#L36

Would you consider changing it? One solution would be to replace it with an explicit switch case with the file names, or even add something like this (rough code):

```js
var methodToRequireFn = {
  ps: () => require("./ps"),
  wmic: () => require("./wmic")
};
```

Thanks!

**Comment by huan** [comment]
Thanks for opening this request.

We'd like to accept a PR to make pidtree to be compatible with the `esbuild`.

We should also consider making pidtree a dual-ESM-CJS-module.

**Comment by simonepri** [comment]
> Would you consider changing it?
Done, feel free to re-open the issue.
