### ISSUE TITLE
ability to return a tree of all processes?

### ISSUE THREAD

**Issue by NullVoxPopuli** [simonepri/pidtree#19]
at present, 
```js
let pids = await pidtree(-1);
```
gives a flat list.

It'd be great if there was a way to get the tree of the pids instead of a flat list

**Comment by simonepri** [comment]
> It'd be great if there was a way to get the tree of the pids instead of a flat list
You can easily build the tree out of the list.

We do this for the CLI here:
https://github.com/simonepri/pidtree/blob/main/bin/pidtree.js

We could in theory add an API that wraps the list to build a tree and then re-use that in the CLI, but I don't have bandwidth to refactore the CLI code at the moment.

If you would like to contribute tho, I'm happy to review PRs.

Thanks!
