### ISSUE TITLE
Add NPM Badge to README

### ISSUE THREAD

**Issue by zixia** [simonepri/pidtree#2]

**Comment by simonepri** [comment]
![image](https://user-images.githubusercontent.com/3505087/37586231-0174b31a-2b5c-11e8-8d83-afdbbbf9e8b0.png)
Is not this? What badge are you talking about?

**Comment by zixia** [comment]
Ah yes, I saw it.

I'm missing it because I'm in China. GFW, you know... ;-/

**Comment by simonepri** [comment]
> I'm missing it because I'm in China. GFW, you know... ;-/

What do you mean?

**Comment by simonepri** [comment]
@zixia 
![image](https://user-images.githubusercontent.com/3505087/37588049-5d03e0fc-2b61-11e8-8b43-02a4b8ba70f3.png)

You don't see this?

**Comment by zixia** [comment]
I mean that the badge image had not shown when I visit the README.md page last time, which made me think we should add it.

But after I had read your reply and I come back to refresh again, the images loaded and displayed.
