### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by lenovouser** [simonepri/pidtree#8]
It would be nice if this project had TypeScript types

**Comment by huan** [comment]
Yes, it's a good suggestion!

To rewrite this project into TypeScript would let us have a better experience for our users.

@simonepri What do you think if we considering to rewrite the code base from JS to TS? It would need some build process in the npm publish process, but it could all be done in a CI like Travis automatically.

**Comment by soyuka** [comment]
I'm really not sure about rewriting in TS, adding some times might be just sufficient especially that there's only one function exposed.

**Comment by simonepri** [comment]
@soyuka thanks
